### ISSUE TITLE
The "TBB" problem

### ISSUE THREAD

**Issue by SSZ1** [iandouglas96/grid_map#1]
When I run the 'catkin_make' command,  it failed and showed as follows:
 'CMake Error at grid_map/grid_map_filters/CMakeLists.txt:35 (find_package):
  By not providing "FindTBB.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "TBB", but
  CMake did not find one.

  Could not find a package configuration file provided by "TBB" (requested
  version 2020.1) with any of the following names:

    TBBConfig.cmake
    tbb-config.cmake

  Add the installation prefix of "TBB" to CMAKE_PREFIX_PATH or set "TBB_DIR"
  to a directory containing one of the above files.  If "TBB" provides a
  separate development package or SDK, be sure it has been installed.
'
I have never met this before. So is there anyone who knows how it this and how to solve it?

**Comment by iandouglas96** [comment]
Sometimes TBB doesn't provide a FindTBB.cmake.  You can find one here: https://github.com/Kitware/VTK/blob/master/CMake/FindTBB.cmake.  Then just make sure that the containing directory is on your CMAKE_PREFIX_PATH.

**Comment by SSZ1** [comment]
OK.Thanks a lot. I have already fix it by commenting the code line out. 




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "iandouglas96/grid_map"                                                                                    ***@***.***&gt;;
Date:&nbsp;Mon, Aug 15, 2022 06:26 AM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:&nbsp;Re: [iandouglas96/grid_map] The "TBB" problem (Issue #1)





 
Sometimes TBB doesn't provide a FindTBB.cmake.  You can find one here: https://github.com/Kitware/VTK/blob/master/CMake/FindTBB.cmake.  Then just make sure that the containing directory is on your CMAKE_PREFIX_PATH.
